### PR TITLE
migration doc

### PR DESCRIPTION
**Pull request by PetraSt**

### CODE REVIEW

**Review by szymongalecki — APPROVED** [review]
Good description of the process. 

In "Steps to restore the Data with an existing DB" you issue those commands from console attached to the droplet in Digital Ocean?

**Review by dprzygocka — COMMENTED** [review]
@PetraSt pls add also information how did you retrieve data from PaaS service

**Comment by PetraSt** [comment]
> @PetraSt pls add also information how did you retrieve data from PaaS service

Done

**Comment by PetraSt** [comment]
> Good description of the process.
> 
> In "Steps to restore the Data with an existing DB" you issue those commands from console attached to the droplet in Digital Ocean?

yes

**Pull request merged**
